### ISSUE TITLE
Delete tag function doesn't delete tag

### ISSUE THREAD

**Issue by shhanson** [shhanson/budgie#24]
Under the Account view, whenever I swipe to delete a tag, the tag does not get deleted.
However, when I go to view my items that referenced said tag, the item's tag is properly set to null.
I've tried refreshing the view, the "deleted" tag still appears.

**Comment by ama2488** [comment]
dis fixed, bra.

but your front end code is JANKY.

my work here is done....

**Comment by shhanson** [comment]
FIXED, please retest and close.

**Comment by shhanson** [comment]
Tested, it works. Closing this as fixed. Thank you!!!
